def main:
  use rad = Math/radians
  return [
    Math/sin(rad(30.0)),
    Math/cos(rad(30.0)),
    Math/tan(rad(30.0)),

    Math/cot(rad(30.0)),
    Math/sec(rad(30.0)),
    Math/csc(rad(30.0)),

    Math/asin(rad(30.0)),
    Math/acos(rad(30.0)),
    Math/atan(rad(30.0)),

    rad(67.4),
    rad(45.0),
    rad(90.0),

    Math/sqrt(9.0),

    Math/ceil(9.75),
    Math/floor(9.75),
    Math/ceil(-8.75),
    Math/floor(-8.75),

    Math/ceil(1.0),
    Math/floor(1.0),
    Math/ceil(0.0),
    Math/floor(0.0),

    Math/round(5.6),
    Math/round(5.5),
    Math/round(5.4),
  ]
