pub mod definition_pruning;
pub mod detach_combinators;
pub mod detach_supercombinators;
pub mod encode_adts;
pub mod flatten;
pub mod linearize;
pub mod resolve_refs;
pub mod simplify_ref_to_ref;
pub mod unique_names;
